ethereum/geth-website

src/components/UI/Header.tsx

Adds home page link to go ethereum header

add home link to go-ethereum header

---

src/components/layouts/Footer.tsx

Fixes footer regression
Fixes: https://github.com/ethereum/geth-website/issues/27

fix footer regression

---

src/components/layouts/Footer.tsx
src/theme/foundations/textStyles.ts

Fixes: https://github.com/ethereum/geth-website/issues/34

fix footer padding issue

---

src/components/docs/Breadcrumbs.tsx
src/components/docs/index.ts
src/pages/[...slug].tsx

- Adds Breadcrumb component for docs pages

Add breadcrumbs to docs

---

src/components/UI/Header.tsx
src/components/UI/HeaderButtons.tsx
src/components/UI/index.ts
src/components/UI/search/Search.tsx
src/components/UI/search/index.ts
src/components/layouts/Layout.tsx
src/components/layouts/MobileMenu.tsx
src/components/layouts/index.ts
src/constants.ts
src/theme/foundations/textStyles.ts

Adds new component `MobileMenu.tsx` according to design utilizing Chakra-UI Modal components.

Mobile menu

---

src/components/UI/downloads/DownloadsHero.tsx
src/components/UI/homepage/HomeHero.tsx
src/pages/index.tsx
src/theme/foundations/textStyles.ts

fix: dark mode body colors

---

src/theme/foundations/textStyles.ts

chore: update h2 font-size

---

src/pages/[...slug].tsx
src/utils/getParsedDate.ts

Adds logic to get last modified data for doc file
Fixes: https://github.com/ethereum/geth-website/issues/58

add lastModified date

---

docs/faq.md

Geth has a Discord server (a server that contains many channels).

Fix Discord typo

---

docs/fundamentals/peer-to-peer.md
docs/getting-started/index.md

Searched for local links that contain domain or `.md` in the path and corrected
- [Fixes #36]

Fix broken links [Fixes #36]

---

src/components/UI/Header.tsx
src/pages/downloads.tsx

This PR fixes #80 by removing the number of releases displayed count message

fix: remove Showing... count message

---

src/components/UI/ButtonLinkSecondary.tsx
src/components/UI/docs/MDComponents.tsx
src/components/layouts/Footer.tsx

fix: external links

---

src/components/UI/Header.tsx
src/components/UI/docs/DocsLinks.tsx
src/components/UI/docs/DocumentNav.tsx
src/components/UI/docs/LinksList.tsx
src/components/UI/docs/MDComponents.tsx
src/components/UI/downloads/DownloadsHero.tsx
src/components/UI/homepage/HomeHero.tsx
src/components/UI/svgs/AddIcon.tsx
src/components/UI/svgs/MinusIcon.tsx
src/pages/[...slug].tsx
src/theme/foundations/textStyles.ts

This PR adds the missing `:hover` color for hero buttons (homepage, downloads page) on dark mode. Fixes #124

Buttons hover color

---

src/components/UI/DataTable.tsx
src/components/UI/downloads/DownloadsTable.tsx
src/pages/downloads.tsx

This PR adds an empty state for platforms without releases (currently only iOS dev builds). Fixes #132

feat: add empty state for platforms without releases

---

docs/developers/contributing.md

Update contribute to the website text

---

docs/developers/geth-developer/code-review-guidelines.md

Removing this whitespace might make the final page look cleaner (Not as much whitespace between terminology and process)
Otherwise this page lgtm cc @jmcook1186

whitespace

---

src/components/UI/docs/MDComponents.tsx

chore: update line-height for docs text

---

docs/developers/dapp-developer/mobile.md
docs/developers/dapp-developer/native-bindings.md
docs/developers/evm-tracing/index.md
docs/faq.md
docs/fundamentals/backup-restore.md
docs/getting-started/consensus-clients.md
docs/getting-started/index.md
docs/interacting-with-geth/javascript-console.md
docs/interacting-with-geth/rpc/graphql.md
docs/interacting-with-geth/rpc/ns-admin.md
docs/interacting-with-geth/rpc/ns-personal.md
docs/tools/abigen.md

Fixes miscellaneous broken links (404s) across the site

Fix broken docs links

---

src/components/UI/downloads/DownloadsHero.tsx
src/theme/components/Button.ts
src/theme/foundations/textStyles.ts

fix: buttons :active/:focus styles

---

src/components/UI/homepage/WhatIsEthereum.tsx
src/pages/index.tsx

- `What is Ethereum` -> `What is Ethereum?`
- `What is Geth` -> `What is Geth?`

Add ? to What is Ethereum and What is Geth

---

src/components/UI/docs/DocsLinks.tsx
src/utils/checkNavLinks.ts
src/utils/index.ts

Add method to open active section on left navbar in docs
Fixes: https://github.com/ethereum/geth-website/issues/164

[UX SUGGESTION] Active section should be expanded on docs page load

---

docs/developers/index.md
docs/fundamentals/index.md

adds links to subsections in section landing pages

add some basic pagination to landing pages

---

.env.local.example
netlify.toml
package.json
src/constants.ts
src/pages/_app.tsx
yarn.lock

This PR adds support for Matomo analytics, fixes #198

feat: Add Matomo analytics
