ethereum/geth-website

- src/components/UI/downloads/DownloadsHero.tsx
- src/components/UI/downloads/DownloadsSection.tsx
- src/components/UI/downloads/SpecificVersionsSection.tsx
- Adds a base case (mobile) of 100% width for GopherDownloads SVG component on /downloads page
- Removes unneeded padding on container.
@ (320px wide)
- [Fixes #38]
> Limit SVG width on mobile [Fixes #38]

- src/components/docs/Breadcrumbs.tsx
- src/pages/[...slug].tsx
This PR removes non-required param from `Breadcrumbs`
> chore: removes non-required param

- src/components/UI/homepage/HomeHero.tsx
Adjusts mobile styling of the homepage h1 in `HomeHero` to match figma
> Update homepage h1 mobile styling to match design

- src/components/UI/downloads/SpecificVersionsSection.tsx
- src/pages/index.tsx
This PR updates updates `SpecificVersionsSection` component layout to match homepage `QuickLinks` layout. Fixes #50
> chore: update SpecificVersionsSection component layout to match homepage

- src/components/UI/Header.tsx
- Adds `white-space: nowrap` to "go-ethereum" text in `Header` component
- [Fixes #79]
> Prevent Header title from wrapping [Fixes #79]

- src/pages/[...slug].tsx
- Removes any extra top margin on the first item shown in markdown content
- [Fixes #75]
> Remove any margin on first markdown item [Fixes #75]

- src/components/layouts/Layout.tsx
- Remove max-width of `container.sm` on mobile screen sizes, replacing with 100%.
- Leaves existing max-width for desktop sizes.
- [Fixes #53]
> Patch responsive width [Fixes #53]

- src/pages/downloads.tsx
> fix: Show older releases button width on mobile

- src/components/UI/docs/DocumentNav.tsx
- src/pages/[...slug].tsx
- Adds a minimum gap between markdown content and the right nav on docs pages
- Shortens the divider in the right nav to prevent overflowing off right edge of screen
- [Fixes #77]
> Add gap between md content and right nav [Fixes #77]

- src/components/UI/downloads/DownloadsTable.tsx
- src/constants.ts
- src/pages/downloads.tsx
This PR updates the default number of displayed rows to 12 and displays the 2 latest linux releases by default. Fixes #78
> fix: show 2 latest releases for linux

- src/components/UI/docs/MDComponents.tsx
- src/pages/[...slug].tsx
**Changes**
- Removed color from `li` elements
- Changed `first-child` to `first-of-type` based on console recommendation for SSR
Fixes: https://github.com/ethereum/geth-website/issues/81
> Docs: Bullet point lists rendering in green 

- src/theme/components/Link.ts
- Updates hover/active/focus link states to match design system
PR:
Figma:
- [Closes #89]
> Adjust link styling for various states [Fixes #89]

- src/components/UI/docs/MDComponents.tsx
- src/pages/[...slug].tsx
- Caps the maxW at 100% width on mobile screen for markdown content section
- Prevents x-overflow of large table or code blocks on mobile
- [Fixes #119]
> Add max width of 100% to markdown content on mobile [Fixes #119]

- src/components/UI/docs/DocumentNav.tsx
Adds hover, active, focus states to DocumentNav links to match design
https://deploy-preview-107--melodious-puffpuff-8e1109.netlify.app/docs/getting-started/installing-geth
- [Fixes #73]
- [Partially addresses #89]
> Fix hover for DocumentNav links [Fixes #73]

- src/theme/index.ts
- Adjusts light mode `primary` color to use `green.700` instead of `green.600` to improve contrast ratio and remove browser a11y warnings
- [Closes #112]
> Adjusts light primary to green.700 for contrast [Closes #112]

- src/components/UI/ButtonLinkSecondary.tsx
- src/components/UI/Header.tsx
- src/components/UI/HeaderButtons.tsx
- src/components/UI/docs/Breadcrumbs.tsx
- src/components/UI/docs/DocsLinks.tsx
- src/components/UI/docs/DocumentNav.tsx
- src/components/UI/docs/LinksList.tsx
- src/components/UI/docs/MDComponents.tsx
- src/components/UI/downloads/DownloadsHero.tsx
- src/components/UI/homepage/HomeHero.tsx
- src/components/UI/homepage/QuickLinks.tsx
- src/components/layouts/Footer.tsx
This PR adds the [missing `legacyBehavior` prop](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-tag) on `NextLink` components that wrap a Chakra `Link`, to fix the nested `<a>` warning/issue
> fix: adds missing legacyBehavior prop [Fixes #98]

- docs/interacting-with-geth/rpc/ns-debug.md
- Removes double slash causing Netlify build errors
> Fix double slash in url

- src/components/UI/docs/DocsLinks.tsx
**Changes**
- Remove defaultIndex from Accordion to have them default closed in `DocsLinks.tsx`
Fixes: https://github.com/ethereum/geth-website/issues/97
> [docs] LHS menu should be closed by default

- .gitignore
- next-sitemap.config.js
- package.json
- public/robots.txt
- yarn.lock
- `yarn add next-sitemap`
- Add `next-sitemap.config.js` config file
- Generates a sitemap and robots.txt file on build (sitemap gitignored)
Similar pattern to Blog sitemap implementation. Also recommended by DocSearch stating it "explicitly exposes URLs to crawl and avoid missing pages that aren't linked from another page"
> Add sitemap and robots.txt

- src/components/UI/downloads/DownloadsTable.tsx
- Checks the users operating system and sets this as the default tab when navigating to the downloads page.
https://deploy-preview-167--melodious-puffpuff-8e1109.netlify.app/downloads
> Add default tab on downloads page based on user OS

- redirects.js
- Updates redirect for `/private-network` path after #169 changes introduced
- Adds legacy directs noted in issue #159
- [Fixes #159]
> Redirects update [Fixes #159]

- src/components/UI/docs/Breadcrumbs.tsx
- Fix bug where Breadcrumbs rendering on root /docs page when a header ID is present
Fixes: https://github.com/ethereum/geth-website/issues/179
> Breadcrumbs on /docs/ page when the URL has a header ID

- redirects.js
Add redirects for broken links in breadcrumbs
Fixes: https://github.com/ethereum/geth-website/issues/182
> Broken links in docs breadcrumbs 

- src/theme/search.css
- Flip position of magnifying glass and "search" text on desktop search component
- Change `<kbd>` styling to use `secondary` instead of `primary`
cc: @nloureiro
> Update styling for search component

- src/components/UI/docs/DocsLinks.tsx
Links that contain hash links at the end were not matching to properly open the correct left nav section in the docs.
This patches the link checked to remove this hash link before checking for a match.
> Fix hash-link bug with left docs nav

- docs/developers/geth-developer/dev-guide.md
- redirects.js
- src/data/documentation-links.yaml
Fixes redirect to /docs/developers/geth-developer/contributing from /docs/developers/contributing
> Add missing redirect
